### ISSUE TITLE
How to add html form in webchat and process it via rasa

### ISSUE THREAD

**Issue by TarunKumar50** [mrbot-ai/rasa-webchat#105]
Hi all,

want to add html like form in start of chat to get user information and
later want a feature where i can ask customer to choose various categories via checkboxes
and then process these information and send it to rasa.

can you please help me here and how can i create it.
@PHLF @znat @TheoTomalty @Hub4IT @dliuproduction @MatthieuJnon

**Comment by znat** [comment]
Hi @TarunKumar50 , this feature is not supported yet. Feel free to submit a PR. 
We look at every issue, so there is no need to mention all contributors/team members individually
