### ISSUE TITLE
ResponseSelector

### ISSUE THREAD

**Issue by nicolasfarina** [mrbot-ai/rasa-webchat#109]
Hi , when i want to use rasa with "ResponseSelector" I get this error.

![captura](https://user-images.githubusercontent.com/52745496/64977270-749bd680-d889-11e9-95ca-06082a95c027.png)

**Comment by znat** [comment]
Hi, we'll be providing a different way to enter responses directly that supports multilingual bots very soon

**Comment by nicolasfarina** [comment]
But the problem is not the retrieval selector?? , is the language?

**Comment by pheel** [comment]
Are you sure this has to do with the ResponseSelector component? i.e. when you remove it from your pipeline, the problem disappears?

Please show us the contents of your credentials settings.

**Comment by nicolasfarina** [comment]
I solved the problem, I had a mistake. thank you.

**Comment by pheel** [comment]
Good to hear!
