### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by radicand** [mrbot-ai/rasa-webchat#110]
I'm running into issues installing directly from Github, and given the amount of issues others have shared on attempting to install this way as well, would you consider publishing the package to npm? It might make it easier to use that way. Thanks for considering!

**Comment by znat** [comment]
Yes @radicand , that is definitely something we need to do!

**Comment by MatthieuJnon** [comment]
This is published to npm now ! Just run `npm i rasa-webchat`
