### ISSUE TITLE
how to get customData value in rasa

### ISSUE THREAD

**Issue by soundaraj** [mrbot-ai/rasa-webchat#114]
** customData: {"userId": "123"}** i want to get this userid value in rasa, how to retrieve it

**Comment by psi43** [comment]
You can access that information on the nodejs side; 
```
socket.on('user_uttered',function(message){
bot_data = {
      "sender": message.customData.userId,
      "message": message.message
  };
});
```
I'm assuming you want to use the userId to differentiate between users, so this should work.

**Comment by soundaraj** [comment]
thanks

**Comment by psi43** [comment]
You're welcome. I struggled with it too until I found out how to do it by myself.

**Comment by xames3** [comment]
> You can access that information on the nodejs side;
> 
> ```
> socket.on('user_uttered',function(message){
>     bot_data = {
>           "sender": message.customData.userId,
>           "message": message.message
>   };
> });
> ```
> 
> I'm assuming you want to use the userId to differentiate between users, so this should work.

Hi @psi43 , could you please guide where to add this? I want to get the timestamp below the messages. Is it possible to do that? Glad if you could help.
