### ISSUE TITLE
Buttons disappear after user input

### ISSUE THREAD

**Issue by ctrado18** [mrbot-ai/rasa-webchat#12]
Hi,

each new bot message like buttons dissappear after user clicks or bot outputs a new button? That is bad to follow dialogue or when bot utter two buttons like for contact or feedback...

How can I prevent this?

I use it as the script version just shown here:
https://github.com/mrbot-ai/rasa-webchat#as-a-script

**Comment by znat** [comment]
Hi, this is how it is supposed to behave. It mimics the behavior of quick replies on Messenger. The title of the button is persisted as a text message in the conversation, so you can always keep track
