### ISSUE TITLE
Chat window crashed, when rasa action utters number instead of string

### ISSUE THREAD

**Issue by aintHuman** [mrbot-ai/rasa-webchat#126]
Was requested by pheel to lodge a ticket here, details outlined at the below link

https://github.com/botfront/botfront/issues/250

I suspected the source of the problem was, and this was confirmed in the above link by pheel, that if an action uttered a response that is not a string then this would crash the chat window.

In my case, I returned a number (float or integer)

**Comment by MatthieuJnon** [comment]
This is fixed 🙂
