### ISSUE TITLE
CSS loader in a react application

### ISSUE THREAD

**Issue by mofortin** [mrbot-ai/rasa-webchat#140]
When building a react application that includes the widget with react-scripts, css are loaded as such : 
```html
<html>
  ....
  <link href="/static/main.css" /> /* this is the normal and expected behaviour */
  <style>
     /* rasa-webchat plain CSS*/
    .conversation-container { /* ... */ }
  </style>
  <body>
  </body>
</html>
```

This makes it impossible for us to customize the CSS since it will always be override.

Can anyone help ?

**Comment by MatthieuJnon** [comment]
Hi, if you write css with rules that have a higher specificity, it should take precedence, just use a class or an id from the elements surrounding where you've placed the widget in the DOM.
For more information on the subject of specificity you can look at https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by mofortin** [comment]
In the long term, it would be nice to be able to pack de CSS in a separate file and fix the multiple import of google fonts. But for the time being I'll go with your solution.
Thanks :)
