### ISSUE TITLE
How to send video from rasa core?

### ISSUE THREAD

**Issue by jonDel** [mrbot-ai/rasa-webchat#15]
How can I send video through rasa core to the webchat? For images, it is straightforward: just setting a "- image: url" in the bot domain file will do the trick. However, there is no '- video' option, only a custom message that could (or could not) be used to send a video instead. Do you think it is an option? Or maybe the only way is adding a 'send_video_url' method in the rasa core socketio class, similar to the send_image_url (https://github.com/RasaHQ/rasa_core/blob/d3a435b6b1b68db90d309d4da38f9247416a825d/rasa_core/channels/socketio.py#L56) method?

**Comment by znat** [comment]
Have a look to the send a video message section in the readme
