### ISSUE TITLE
Links in messages should be highlighted and clickable

### ISSUE THREAD

**Issue by znat** [mrbot-ai/rasa-webchat#2]
See discussion here: https://github.com/mrbot-ai/rasa-addons/issues/15

**Comment by amn41** [comment]
I'm happy to work on this - shall I give it a try?

**Comment by znat** [comment]
That would be wonderful!

Le ven. 5 oct. 2018 13 h 04, Alan Nichol <notifications@github.com> a
écrit :

**Comment by amn41** [comment]
Awesome, I'm having a bit of trouble with npm, but it should really just be this diff:

file:
`/src/components/Widget/components/Conversation/components/Messages/components/Message/index.js`

```
 import React, { PureComponent } from 'react';
 import { PROP_TYPES } from 'constants';
+import { linkify } from 'linkify';
 
 import './styles.scss';
 
 class Message extends PureComponent {
   render() {
+    const content = linkify(this.props.message.get('text'));
     return (
       <div className={this.props.message.get('sender')}>
         <div className="message-text" >
-          <p style={{ margin: '0' }}>{this.props.message.get('text')}</p>
+          <p style={{ margin: '0' }}>{content}</p>
         </div>
       </div>
     );
```

+ adding linkify to the package.json. @znat could you maybe give it a quick try?

**Comment by znat** [comment]
@amn411 - It's done and published
