### ISSUE TITLE
Bug with starting a conversation via button click

### ISSUE THREAD

**Issue by akelad** [mrbot-ai/rasa-webchat#30]
If you click on a button to open the chat window, it opens the chat (but doesn't send the initial payload). You then chat to it for a bit, then close the window and open it again and then the initial payload gets sent in the middle of the conversation.

This is using version 0.4.2 in the webchat widget, basically it shouldn't send the initial payload if the conversation is already happening

**Comment by znat** [comment]
@akelad yes, this is a known bug that should be fixed with 0.5.x

**Comment by akelad** [comment]
alright! i kind of had that suspicion, we'll upgrade as soon as we figure out the socket bug... I'll close this
