### ISSUE TITLE
Unable to use Widget Component

### ISSUE THREAD

**Issue by Ripza** [mrbot-ai/rasa-webchat#32]
Hello. Thanks for this widget, it has a lot of potential.

For two months I use rasa-webchat without using React (only using html and script).

Now using React I'm trying to import the Component to my project using the steps in README, but it appears this error when I try to use the Component:

`
ERROR in ./node_modules/rasa-webchat/index.js 9:6
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type.
|
|     ReactDOM.render(
>       <Widget
|         socketUrl={args.socketUrl}
|         socketPath={args.socketPath}
 @ ./src/components/WebChat/WebChat.js 19:0-38 38:29-35
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src/index.js`

I'm using React 16.6.3 with Webpack 4.26 and node 10.14.1. 

Someone could help me? :( 

Thanks

**Comment by dliuproduction** [comment]
Hi, can you provide the snippet where you import and render the component? The error seems weird as the `init` method in the plugin mode is called. The problem might be in the usage as a react component.

**Comment by Ripza** [comment]
Sure!

```javascript
import React, { Component } from 'react'
import { Widget } from 'rasa-webchat'

class WChat extends Component {

  buildChat = () => {
    return (
      <Widget
        interval={2000}
        initPayload={"/get_started"}
        socketUrl={"http://localhost:5500"}
        socketPath={"/socket.io/"}
        title={"Title"}
        inputTextFieldHint={"Type a message..."}
        connectingText={"Waiting for server..."}
        embedded={true}
        params={{
          images: {
            dims: {
              width: 300,
              height: 200
            }
          },
          storage: "local"
        }}
      />
    )
  }

  render() {
    return (
      <div className="webchat-container" >
        {this.buildChat()}
      </div>
    )
  }
}

export default WChat;
```

Calling in this router: 
```javascript

import React from 'react';
import { BrowserRouter, Switch } from "react-router-dom";
import WChat from "./components/WebChat/WebChat";

export default () => {

 return (
   <BrowserRouter>
    <Switch>
      <Route path="/web-chat/" component={WChat} />
    </Switch>
   </BrowserRouter>
 )
}

```

Another example:

```javascript
import WChat from './components/WebChat/WebChat'

ReactDOM.render(<WChat />, document.getElementById('app'));
```

I tried a lot of differents ways, but all responds the same.

This is my webpack: 

```javascript
const HtmlWebpackPlugin = require("html-webpack-plugin");
module.exports = {
  entry: './src/index.js',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader'
          }
        ]
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'html-loader'
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 8192
            }
          }
        ]
      }
    ]
  },
  output: {
    filename: 'bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'public/index.html'
      //favicon: 'public/favicon.ico'
    })
  ],
  devServer: {
    host: '0.0.0.0',
    port: 3000,
    overlay: true,
    historyApiFallback: true,
    open: true
  }
};
```
and .babelrc:

```javascript
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}

```

Thanks for your time

**Comment by dliuproduction** [comment]
Thanks for the example. We actually ran into the same problem on some environments, but not all. What OS are you running?

**Comment by Ripza** [comment]
I'm running Ubuntu Desktop 18.10

**Comment by Ripza** [comment]
Hmmm ... I downloaded the repo using the contributors steps and linked the import to the location of the repo. When I started the project it runs perfectly, but with this change in the package.json in rasa-webchat:

    "webpack-cli": "^3.1.2",

When I tried without it the compiler said this:


```javascript

/rasa-webchat/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined

```

Using node 10.14.1.

**Comment by dliuproduction** [comment]
Hi @Ripza. Can you test with branch [fix/package-lock](https://github.com/mrbot-ai/rasa-webchat/tree/fix/package-lock)? I added fixes for webpack and build scripts.

**Comment by mounabenayed** [comment]
Hello, 
I have the same issue but the newer version of rasa-webchat. Any help please ?

**Comment by CKanishka** [comment]
> Hello,
> I have the same issue but with the newer version of rasa-webchat. Any help please ?

Yeah I am also having the issue when I try to run it in a Linux environment.
