### ISSUE TITLE
Images: expose dimensions as parameters

### ISSUE THREAD

**Issue by znat** [mrbot-ai/rasa-webchat#4]

**Comment by jonDel** [comment]
Second that.

**Comment by znat** [comment]
the requirement has evolved a little bit:
- if **no** dimensions are set, then crop scale to default (300x200) -> no breaking changes for existing users
- if **both** dimensions are set, then keep current behavior (crop scale to dimension)
- if an empty array is set `image:{dims:[]}` - then let the image take its space up to 100% of the width without constraining the height. Useful for projects using the widget full screen
There are two other cases but I don't think we need to implement them right now:
- `image:{dims:[x,0]}`: constrained width but no constraint on height
- `image:{dims:[0, y]}`: constrained height but no constraint on width.

@TheoTomalty thoughts?

**Comment by dliuproduction** [comment]
Implemented in PR #20.
