### ISSUE TITLE
Video/Image Not Showing

### ISSUE THREAD

**Issue by arni5na** [mrbot-ai/rasa-webchat#41]
Hi there! I'm trying to send a video/image to the chat UI from Rasa but this is what i'm getting:

![screen shot 2018-12-16 at 2 51 48 pm](https://user-images.githubusercontent.com/45895721/50050886-2b73f600-0142-11e9-9e27-13e5c834c837.png)

This is a snippet of my actions.py code:
![screen shot 2018-12-16 at 2 53 30 pm](https://user-images.githubusercontent.com/45895721/50050907-637b3900-0142-11e9-9ce8-80231429359a.png)

I have an actions server and my socket server code is on another Python file. If I use the SocketIOOUtput Class, it will ask me for a recipient ID which I'm not sure where to get. I'm pretty new to Python and Rasa. Any help would be much appreciated!

**Comment by arni5na** [comment]
Update: I used dispatcher.utter_attachment(message) with message = {
                "type":"video",
                "payload":{
                    "title":"Link name",
                    "src": "https://youtu.be/f3EbDbm8XqY"
                }
            }

But it still shows as text in the chat window:
![screen shot 2018-12-16 at 4 28 58 pm](https://user-images.githubusercontent.com/45895721/50051573-f4a4dc80-014f-11e9-8f0a-86d7af8cbcef.png)

**Comment by znat** [comment]
With Rasa Core it must follow the template schema.
So for an image:
```
{
  text: ...,
  image: ...
}
```

**Comment by arni5na** [comment]
I was able to send an image by adding it in the templates of the domain file, but I can't send through the custom actions. I changed the value of the message variable in my actions file into this:
message = {
            "attachment":{
                "type":"image",
                "payload":{
                    "text":"Test",
                    "image": "img.jpg"
                }
            }
        }

Then I used the dispatcher to send it, but it still doesn't show the image. I'm not sure if I'm in the right track here. Is it possible to send image/video through the custom actions or it can only be done through the domain file?

**Comment by bing-zhub** [comment]
I have encountered the same problem with you, attachment should be part of response. The reality is that it is part of text. I don't know if you have solved this problem.

**Comment by arni5na** [comment]
Sorry, I got busy... Anyway, it seems that we need the Rasa core output channel of the webchat to send the video. I checked the rasa-addons link where we supposed can get it but I didn't find it there...

**Comment by arni5na** [comment]
It's still not working using custom message. This is the video JSON data I sent to the UI:
message = {
                "attachment":{
                    "type":"video",
                    "payload":{
                        "title":"Link name",
                        "src": "https://www.youtube.com/watch?v=f3EbDbm8XqY"
                    }
                }
            }

I did a debug on the UI and it's acknowledging that it received the data as video but it just doesn't show it.

**Comment by arni5na** [comment]
Got it finally resolved. These are the steps I did:

In CollectingDispatcher class, I added this function:
```
    def utter_response(self, message: Dict[Text, Any]) -> None:
        """Send a message to the client."""
        
        self.messages.append(message)
```

In SocketIOOutput class of the socketio module, I added the following:
```
    def send_response(self, recipient_id: Text, message: Dict[Text, Any]):
        self._send_message(self.sid, message)
```

In the Dispatcher class of the dispatcher module, I made the following changes:
```
    def utter_response(self, message: Dict[Text, Any]) -> None:
        """Send a message to the client."""

        bot_message = BotMessage(text=message.get("text"),
                                 data={"elements": message.get("elements"),
                                       "buttons": message.get("buttons"),
                                       "attachment": message.get("video")})

        self.latest_bot_messages.append(bot_message)
        self.output_channel.send_response(self.sender_id, message)
```

**Comment by arni5na** [comment]
Sorry, above fix caused some issue when dispatching messages other than video attachment. I made changes to the send_custom_message function in socketio instead:

`def send_custom_message(self, recipient_id: Text,
                            elements: List[Dict[Text, Any]]) -> None:
        """Sends elements to the output."""
        #print(">>>elements:", elements)
        message = ''
        try:
            if not any('attachment' in d for d in elements):
                message = {"attachment": {
                    "type": "template",
                    "payload": {
                        "template_type": "generic",
                        "elements": elements[0]
                    }}}
            else:
                message = elements[0]
            self._send_message(self.sid, message)
        except Exception as e:
            print("Error sending custom message:", e)
`
