### ISSUE TITLE
Retrieving customData in core actions

### ISSUE THREAD

**Issue by ivopisarovic** [mrbot-ai/rasa-webchat#42]
_**I have set a react prop `customData={{"userId": "123"}}` according to the README page. I have successfully connected rasa-webchat to rasa_core via socketio. I cannot get that `customData` in my custom rasa_core actions.**_ 

**Issue:** Missing a hint in README on how to retrieve this `customData` in rasa_core. This may be very useful for many novices like me. 

**The general problem:** Identification of the user in the rasa core actions. To achieve this I need either:
- Extract `senderId` from rasa-webchat component in react frontend and attach this id to the user in the database.
- Supply custom `senderId` or `customData` to rasa-webchat.

However, I cannot do any of these. I cannot access `senderId` in the react component. And I cannot set my custom `senderId`. The rasa-webchat react component is closed.

**Comment by znat** [comment]
You should be able to retrieve the `senderId` in the tracker (latest_message)

**Comment by ivopisarovic** [comment]
I created a PR. https://github.com/mrbot-ai/rasa-webchat/pull/48

**Comment by znat** [comment]
Yes you can use it as a user id with 0.5.x by setting the `session_persistence` param to `true` in the `socketio` channel in the credential yaml file

**Comment by ivopisarovic** [comment]
Yes, that is good for persisting the same id across sessions. However, it does not solve pairing with a user that is already logged in on the frontend. So I have to send some custom data anyway. Am I right?

**Comment by ivopisarovic** [comment]
No response, hence I am right :D

**Comment by znat** [comment]
The we chat generates the session id string randomly. But you could change that behaviour by setting your session_id as a prop. It might not be very secure as the socket is open though

**Comment by ivopisarovic** [comment]
I have already solved the problem using `customData`.

However, I am still interested :) I went through the code but I cannot find the line where it reads `session_id` from prop. So I do not believe changing session id is so easy. :) Please, can you point me to the code where this happens?

**Comment by znat** [comment]
It doesn't yet... I was suggesting a possible addition. But since you found your way there's no need

**Comment by ivopisarovic** [comment]
Aha! I do understand now. Thanks for explaining :) Yes, it would be fine to have such a prop. But doing it via `customData` is simpler, so there is no need for that now.

**Comment by ramsesdm** [comment]
@ivopisarovic  could you please explain how did you solve the problem with `customData`?
Thanks

**Comment by ivopisarovic** [comment]
@ramsesdm Sure. Look at [README](https://github.com/mrbot-ai/rasa-webchat#rasa-core). I have explained it there. You need to create a custom channel in Rasa Core to handle custom data on backend.

**Comment by ramsesdm** [comment]
thanks @ivopisarovic already working

**Comment by shivangpatel** [comment]
@ramsesdm @ivopisarovic How to do it with latest rasa ? Where i need to write code for it ?

**Comment by ivopisarovic** [comment]
@shivangpatel Sorry, I am still using the older version.
