### ISSUE TITLE
Chat window running a custom Action on opening

### ISSUE THREAD

**Issue by mrcoolhp** [mrbot-ai/rasa-webchat#43]
Hello Everyone, 

Thanks for this Chat Widget first of all, I have tried implementing this chat widget, everything works fine except on opening html page chat windows runs a custom action by default which is not supposed to happen. 
How to make default utter greet message on first load ?

Please help.

Thanks,
Hari

**Comment by ivopisarovic** [comment]
Hi Hari,
you can set `initPayload: "/get_started"` attribute of the chat widget. This payload is sent to backend  for the first time the chat is opened. On backend you need to prepare a story like: 
```
## welcome
* get_started
  - utter_introduction1
```
Where `get_started` is the payload. It works fine for me. I am using React version of the widget. 

However, it is worth to mention, it is sent only once per browser. To repeat it, you have to delete `chat_session` in browser's local storage.

Ivo

**Comment by saxh** [comment]
> Hi Hari,
> you can set `initPayload: "/get_started"` attribute of the chat widget. This payload is sent to backend for the first time the chat is opened. On backend you need to prepare a story like:
> 
> ```
> ## welcome
> * get_started
>   - utter_introduction1
> ```
> Where `get_started` is the payload. It works fine for me. I am using React version of the widget.
> 
> However, it is worth to mention, it is sent only once per browser. To repeat it, you have to delete `chat_session` in browser's local storage.
> 
> Ivo

hi Ivo ,it dose work for me . do you mind saying it clearly for me?

**Comment by ivopisarovic** [comment]
@saxh I wrote it as clearly as I can. Try to describe your exact step-by-step scenario that leads to the problem. You can also send snippets of code showing your configuration of the widget and stories.

**Comment by ivopisarovic** [comment]
This seems ok. Stupid question, have you retrained rasa core before running it again?

**Comment by saxh** [comment]
> This seems ok. Stupid question, have you retrained rasa core before running it again?

yes....of course

**Comment by ivopisarovic** [comment]
Sorry, in that case, I cannot help you anymore. You must wait for another's help. Or just try to debug it yourselves. Create a log on the backend and see what is coming from the frontend and how the rasa core is interpreting it. 
Are you using the latest master versions of Rasa Core and Rasa webchat?

**Comment by znat** [comment]
@saxh  Note that if you use local/session storage, then it will send the payload only once when the conversation is initialized. If you want to see this message again you need to explicitly clear the local storage in your browser console:
```
localStorage.clear()
sessionStorage.clear()
```
