### ISSUE TITLE
Escalation to human

### ISSUE THREAD

**Issue by dfiore-ch** [mrbot-ai/rasa-webchat#56]
Hi
It is a common requirement to escalate a chat from a chatbot to a human. It would be great if you can integrate a functionality, so that the user manually initiates an escalation or automatically by a special message form the socket.io server. 
This could be easily implemented by switching to another, alternative socket.io server if requested by the user or by the special message/event from the socket.io server.
Greets

**Comment by znat** [comment]
that should be handled server-side (see events to pause the tracker)
