### ISSUE TITLE
Send response in raw HTML

### ISSUE THREAD

**Issue by tomgrassmann** [mrbot-ai/rasa-webchat#58]
Hello!

Is there a way to send a Message as raw HTML?

I've got a custom action that's getting called, generating a Message containing some links retrieved from a database, which then are saved into a slot, which content is than echoed in the the Bots response.

At the Moment, the HTML seems to get escaped, so I'm getting

<a href="http://127.0.0.1/test/****>****Title</a>, where the URL is a clickable Link instead of
just showing ****Title as a clickable Link.

Is there a way of changing this behavior? Is this even a problem with the chat script or is this an issue with Rasa?

**Comment by znat** [comment]
@tomgrassmann you can use markdown `[click here](http://link.to)`

**Comment by netcarver** [comment]
@znat Hello Nathan. I think I'm hitting this issue as well.

If I output a link in markdown format, the [title part] seems to be totally ignored and the url string is appearing as both the title text and the href of the generated anchor.

Here's an example. I added a fake accounting topic entry to my FAQ document that has a markdown link in it...

![screeny-0066](https://user-images.githubusercontent.com/16049/53824263-747e5e00-3f6b-11e9-9210-22e1e477be7b.png)

... and here's how it's rendered by rasa-webchat...
![screeny-0065](https://user-images.githubusercontent.com/16049/53824324-9841a400-3f6b-11e9-84d7-d4a13b3a396d.png)



The same link renders correctly under scalableminds chatroom.

**Comment by netcarver** [comment]
@MatthieuJnon Looks like [this line](https://github.com/mrbot-ai/rasa-webchat/blob/master/src/components/Widget/components/Conversation/components/Messages/components/Message/index.js#L29) might be the problem. Looks like it ignores the title in the renderer.

**Comment by MatthieuJnon** [comment]
You're absolutely right, i'll fix this in a few hours

**Comment by netcarver** [comment]
@MatthieuJnon Hi Matthieu, thank you - that would be appreciated!

I think I spoke too soon about no other problems with the Markdown rendering - there seems to be an issue with converting newlines in bot replies to html breaks as well. Will look to open a separate issue for that later.

**Comment by MatthieuJnon** [comment]
The named link issue has been fixed in the latest version 0.5.6, thank you for your documentation of the issue. 
And please do open an other issue on that newline to html breaks problem.

**Comment by khldOdoo** [comment]
How can i embed an iFrame  ? i am trying to respond with google maps but it doesnt seem to accept iframe
