### ISSUE TITLE
CORS error connection to RASA running on Docker

### ISSUE THREAD

**Issue by ramsesdm** [mrbot-ai/rasa-webchat#70]
I am running RASA on Docker but trying to connect from the webchat I am getting the following error:
`Access to XMLHttpRequest at 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=McN1g06' from origin 'http://localhost:808' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Here my nlu_config.yml
`language: "en"
cors_origins:
- "*"
pipeline: "spacy_sklearn"`

Also I created a credentials.yml file
`socketio:
    user_message_evt: user_uttered
    bot_message_evt: bot_uttered`

and added it to the docker-compose command for rasa_core
`command: start --core models -c rest --endpoints config/endpoints.yml -u current/ --credentials config/credentials.yml`

I am missing something?

PD: Rasa version 0.14

**Comment by znat** [comment]
channel should be `socketio` and not `rest`
