### ISSUE TITLE
CustomData - Can not make it work

### ISSUE THREAD

**Issue by EmannuelRoque** [mrbot-ai/rasa-webchat#78]
Hi,

I trying to set a slot from a customData using webchat initial script.

I am definitively stuck.

According with README.md file:

<div id="webchat"/>
<script src="https://storage.googleapis.com/mrbot-cdn/webchat-0.5.6.js"></script>
<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "/get_started",
    interval: 1000, // 1000 ms between each message
    customData: {"link_Id": "123"}, // arbitrary custom data. Stay minimal as this will be added to the socket
    socketUrl: "http://localhost:5500",
    socketPath: "/socket.io/",
    title: "Title",
    subtitle: "Subtitle",
    inputTextFieldHint: "Type a message...",
    connectingText: "Waiting for server...",
    hideWhenNotConnected: true,
    fullScreenMode: false,
    profileAvatar: "http://to.avat.ar",
    openLauncherImage: 'myCustomOpenImage.png',
    closeLauncherImage: 'myCustomCloseImage.png',
    params: {
      images: {
        dims: {
          width: 300,
          height: 200,
        }
      },
      storage: "local"
    }
  })
</script>

Then I am editing:

/usr/local/lib/python3.6/dist-packages/rasa_core/channels/socketio.py 

        @sio.on('session_request', namespace=self.namespace)
        def session_request(sid, data):
            logger.debug(data.get("link_Id"))
            if data is None:
                data = {}
            if 'session_id' not in data or data['session_id'] is None:
                data['session_id'] = uuid.uuid4().hex
            sio.emit("session_confirm", data['session_id'], room=sid)
            logger.debug("User {} connected socketIO endpoint."
                         "".format(sid))

How can I get de customData in scocketio.py and pass to slot?

If Its easier, how can I just get the customData in sequence to session_id? 

With de customData and session_id I will write in the database and track from where the client got to the chat bot landing page.

Can someone provide a simple example?

Thanks...

**Comment by sfrpl** [comment]
If it helps.. you can use initPayload for filling the slot

**Comment by SarahGrs** [comment]
EmannuelRoque   did you solve it?

**Comment by znat** [comment]
Hi, so `userData` was implemented before rasa core 0.11 when it was easy to just attach data to the `OutputChannel` that would travel as a side car to the message through the Core steps. And you could get it back in the actions. Now it's not the case anymore. So you have 2 possibilities:
- Implement your own SocketIO channel and deal with `userData` yourself
- Use `initPayload` as @sfrpl  suggests

**Comment by EmannuelRoque** [comment]
Hi,
I customized the socket io channel to write in the database when the new message is received - including the sender id.

After that I use the sender id in a custom action to query the database and return the customdata sended by the chatclient.

Thanks
Emannuel Roque

**Comment by shivangpatel** [comment]
@EmannuelRoque Can you share code ? And some brief explanation too.
