### ISSUE TITLE
How to use via python?

### ISSUE THREAD

**Issue by ctrado18** [mrbot-ai/rasa-webchat#80]
Hi,

I am new and struggle to find out how to use it:

I want to use it via python as the file _`chat.py`_ and have:

```
def run_bot(serve_forever=True):
   interpreter = RasaNLUInterpreter('./models/nlu/test')
    agent = Agent.load('./models/dialogue', interpreter = interpreter)
    
    input_channel = WebChatInput(static_assets_path=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'start.html'))
    agent.handle_channel(SocketInputChannel(5500, "/bot", input_channel))

```

and:
```

<div id="webchat"/>
<script src="https://storage.googleapis.com/mrbot-cdn/webchat-0.4.1.js"></script>
<script>
    WebChat.default.init({
        selector: "#webchat",
        initPayload: "",
        interval: 0, // 1000 ms between each message
        customData: {"userId": "123"}, 
        socketUrl: "127.0.0.1:5500",
        socketPath: "/socket.io/",
        title: "Hi",
        subtitle: "Chat"
    })
</script>
```

But if I just start via chat.py and call start.html no answer from rasa comes back?

Do I miss something?

I am using rasa core 0.10.4

**Comment by ctrado18** [comment]
I just found out that everything is right, but I needed to add the http before the url...

`socketUrl: "http://127.0.0.1:5500",`

I don't know the reason, but it works...

**Comment by GraphGrailAi** [comment]
@ctrado18  hi, could you provide full file `chat.py` with imports, etc, trying get it to work, but nothing
