### ISSUE TITLE
developing widget

### ISSUE THREAD

**Issue by D063520** [mrbot-ai/rasa-webchat#83]
Hi,

I wanted to change some code and I was wondering how you set this project up to develop it. I tried:

npm run-script dev

but the webpage is empty. I could successfully integrate the component in a existing project.

Thank you
D063520

**Comment by znat** [comment]
The webpage is probably empty because the param hideIfNotConnected is true
and there's no Core instance running

Le dim. 5 mai 2019 10 h 43, Dennis Diefenbach <notifications@github.com> a
écrit :

**Comment by D063520** [comment]
Probably you are right, thank you!
